spring:
  application:
    name: smart-library

  datasource:
    url: jdbc:postgresql://localhost:5433/smart_library_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000
  file-storage:
    upload-dir: ./uploads/pdf-assets